src/TheWorld/Controllers/AuthController.cs
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Mvc;
using TheWorld.Models;
using TheWorld.ViewModels;

namespace TheWorld.Controllers
{
    public class AuthController : Controller
    {
        private SignInManager<WorldUser> _signInManager;

        public AuthController(SignInManager<WorldUser> signInManager )
        {
            _signInManager = signInManager;
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Trips","App");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel vm, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var signInResult = await _signInManager.PasswordSignInAsync(vm.Username,
                                                        vm.Password, true, false);

                if (signInResult.Succeeded)
                {
                    if (string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Trips", "App");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Username or Password incorrect");
                }
            }

            return View();
        }

        public async Task<ActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await _signInManager.SignOutAsync();
            }

            return RedirectToAction("Index", "App");
        }
    }
}

src/TheWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>

<body>
<div id="sidebar">
    @if (User.Identity.IsAuthenticated)
    {
        <img src="~/img/profileRicky.jpg" alt="Profile Pic" class="headshot"/>
        <span id="username">@User.Identity.Name</span>
    }
    <ul class="nav">
        <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
        <li><a asp-controller="App" asp-action="About">About</a></li>
        <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
@if (User.Identity.IsAuthenticated)
{
    <li><a asp-controller="App" asp-action="Trips">My Trips</a></li>
    <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
}
    </ul>
</div>
    <div id="wrapper">

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button id="sidebarToggle" class="btn btn-primary">
                            <i class="fa fa-angle-left"></i>
                        </button>
                    </li>
                </ul>
                <a asp-controller="App" asp-action="Index" class="navbar-brand">The World</a>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-save"></i> Save
                        </a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-print"></i> Print
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <div id="main" class="container-fluid">
            <div>
                @RenderBody()
            </div>
        </div>

        <div id="footer" class="container-fluid">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <h4 class="text-center text-info">&copy; 2015 The World Ltd.</h4>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>

    @RenderSection("Scripts", false)

</body>

</html>